### ISSUE TITLE
beforeResponse and transformResponse acting differently

### ISSUE THREAD

**Issue by ccristobal-skillz** [httptoolkit/mockttp#61] opened 2021-11-05 20:53 UTC
Hello,

I am using mockttp in order to retrieve specific responses, modify them, then pass them through to the original requestor. 

However, I am finding that I am having issues using the `beforeResponse` `PassThroughHandlerOptions` but I am able to successfully use the `transformResponse` property to change the JSON body. The issue with me using the `transformResponse` property instead, is that I don't have access to the original response body and cannot programmatically change it, rather, I am reading a json file into an object which I pass to the `transformResponse`.

```
  const requestLogger = (request: CompletedRequest) => {
    console.log(`Request for: ${request.url}`);
    return;
  };

  const fileContents = fs.readFileSync(
    path.resolve(__dirname, '../../config/mockttp/info.json'),
    'utf8'
  );
  
  const fileToJson = JSON.parse(fileContents);

  Object.entries(fileToJson).forEach((item) => {
    const key = item[1]['key'];
    item[1]['value'] =
      key == 'value1'
        ? 'false'
        : key == 'value2'
        ? 'true'
        : key == 'value3'
        ? 'false'
        : key == 'value4'
        ? 'true'
        : item[1]['value'];
  });

  const transform: ResponseTransform = {
    updateJsonBody: fileToJson,
  };

  const customResponse = (response: CompletedResponse) => {
    console.log(response);
    return { ...response, body: fileToJson };
  };
```
The below works:
```
    await Promise.all([
      this.mockServer.get('/info').always().thenPassThrough({
        transformResponse: transform,
        beforeRequest: requestLogger,
      }),
      this.mockServer.anyRequest().thenPassThrough({
        beforeRequest: requestLogger,
      }),
    ]);
 ```
But this fails
```
    await Promise.all([
      this.mockServer.get('/info').always().thenPassThrough({
        beforeRequest: requestLogger,
        beforeResponse: customResponse,
      }),
      this.mockServer.anyRequest().thenPassThrough({
        beforeRequest: requestLogger,
      }),
    ]);
```

I've tried using the `body` and `json` return properties of `beforeResponse` all with strings, uint8 buffers, or json object and still no success.

Any idea what is going on?

**Comment by pimterry** [comment] 2021-11-08 11:32
The example code here definitely won't work - the `body` param does need to be a string or Buffer. If you want to pass a JSON object directly, you're looking for the `json` param. The full types are documented [here](https://httptoolkit.github.io/mockttp/interfaces/requestHandlers.PassThroughHandlerOptions.html#beforeResponse).

You did mention you tried that, but it doesn't work. How doesn't it work? Are there errors? It would be very helpful if you could share a complete failing example, so I can reproduce this for myself.

**Comment by ccristobal-skillz** [comment] 2021-11-08 21:36
@pimterry, is there some way I can print the output of the response as it is sent as a passthrough? I'm trying to debug the receiving end of the processed response.

**Comment by ccristobal-skillz** [comment] 2021-11-09 00:08
![image](https://user-images.githubusercontent.com/87995947/140837673-190ecd9f-641f-48ec-8dfc-67dd898c8372.png)
![image](https://user-images.githubusercontent.com/87995947/140837696-6c732f39-6bd1-4535-8c0b-63b879cf60a2.png)

Something that I found interesting was that an original response size (according to the header) is 4325 but a recalculated header size is much much bigger. I am making modifications to the JSON body from one string to another, ('TRUE' -> 'FALSE' and vice versa), does that seem correct for the size to be that drastic of a change?

**Comment by ccristobal-skillz** [comment] 2021-11-09 01:44
![image](https://user-images.githubusercontent.com/87995947/140846304-ab1a8f30-c5e9-4145-9ca8-81f80de2e659.png)
Using the transformResponse here, the byte length is calculated correctly.

**Comment by ccristobal-skillz** [comment] 2021-11-09 03:59
![image](https://user-images.githubusercontent.com/87995947/140859206-52ce5ee7-e037-44f4-99a7-c8084867ea86.png)
After a night of debugging through mockttp handlers, I have come to the conclusion that compression is my issue. After inserting a snippet which uses `zlib` to compress the body, I was able to properly use the `beforeResponse` callback.

**Comment by pimterry** [comment] 2021-11-09 08:50
Mockttp does handle compression automatically in some cases, so that could plausibly cause this. There's likely other solutions available to work around this as well, like dropping compression headers and similar.

It's very difficult to help or make suggestions without exploring the specific behaviour up close though. Can you please share a basic demo of the issue, so I can run this myself?

**Comment by ccristobal-skillz** [comment] 2021-11-09 19:27
So my application seems to be very strict in that it only accepts encoding of gzip. Any other response will cause a failure. 

And I'm sorry I'm not able to provide quite as much detail as you would like - I'm working with some proprietary code and I can't share the details.

That being said, I did find out that I can gzip the json data in my response handler prior to returning it as a `CallbackResponseMessageResult` so I can process my custom responses correctly, right now.

Would you still be willing to support automatic compression based on the `content-encoding` header?

**Comment by pimterry** [comment] 2021-11-12 18:54
Ah, I see. Ok, this makes sense.

Right now, Mockttp effectively delegates encoding to you when you're using beforeRequest/Response. If it didn't do that, it'd be totally impossible to do provide your own already-encoded data, which is required to do things like injecting badly encoded data (e.g. to test decoding errors) or using any unrecognized encodings. transfromX does do encoding automatically, because it's a simpler API and that's the most common case, and because the beforeX methods are available to act as an alternative that covers those edge cases.

It is fairly easy to do encoding manually, if you want - I've published a separate library (used internally by the transformX options) that does exactly this, just given a body buffer & content-encoding header: https://www.npmjs.com/package/http-encoding

That said, I'm open to adding support for this, or at least better documenting it, if that's something you'd be interested in working on?

Any fix would need to be backwards compatible, so nobody supplying custom encoded or intentionally not-encoded data today starts having issues. That makes this difficult!

Long term, I think I could be persuaded that this isn't a good default generally, and manually encoding should be opt-in instead. That would mean eventually moving to a callback return type something like:

```
{
   // Decoded data, encoded automatically:
	body: string | Buffer | Uint8Array,
   // JSON body, encoded automatically:
   json: any,
   // Encoded data, used untouched:
   encodedBody: Buffer | Uint8Array
   // ^ Only one of the above allowed - reject responses that set more than one

   /* same non-body fields as today... */
}
```

What do you think?

We can't do that today without breaking changes, but we can plan to move in that direction. I think the cleanest approach to start with would be documenting the current behaviour, and adding a new `decodedBody` field you can return, in which case the body is encoded for you automatically.

Then, later on, we bump to v3 and say "decodedBody is now body, json now encodes automatically, if you do want to disable automatic encoding use the new encodedBody field". That's a fairly easy migration for anybody who cares.

How does that sound? Interested in putting together a PR?

**Comment by ccristobal-skillz** [comment] 2021-11-15 18:11
That sounds like a good option! I'll see what I can do this week/weekend and try to find some time to work on it.

**Comment by pimterry** [comment] 2022-04-29 18:01
This is now fixed in the just-released Mockttp v3. All callbacks, incuding beforeRequest and beforeResponse, will now do the same as transformRequest/Response and automatically encode the returned body to match the final `content-encoding` of the request/response.

This is a breaking change (part of why it's v3), but you can get the old behaviour back by returning `rawBody` with a pre-encoded buffer instead of `body`/`json` in the callback. Raw bodies are sent as they are, with no encoding step. Thanks for filing this!

**Closed by pimterry** 2022-04-29 18:01 UTC
