### ISSUE TITLE
How to get response from a single api and passthrough each other api?

### ISSUE THREAD

**Issue by huviivuh** [httptoolkit/mockttp#169] opened 2024-04-11 14:44 UTC
Hi, i use mockttp to catch mobile api response.

I use:

server.forPost(/.*\/example-path\/.*/).thenPassThrough({
beforeResponse: (response) => {
// Some code
}
});

It work fine but other api links don't work at client and the app dose not working.

 When i add code:

server.forPost(/.*\/example-path\/.*/).thenPassThrough({
beforeResponse: (response) => {
// Some code
}
});
server.forAnyRequest().thenPassThrough(); 

I got error:  "Failed to handle request: socket hang up" from */example-path/*

What can i do now?

**Comment by pimterry** [comment] 2024-04-12 06:26
Hi @huviivuh. When you add two rules like this (using normal matching like `forPost`, `forAnyRequest` etc) what happens by default is that the first rule runs (for the first matching request) and then the second rule runs (for the second matching request), etc. This lets you define a chain of behaviours that run in series. By default the last rule keeps running forever once there are no more rules to fall back to.

For cases like this though I don't think that's what you want. Instead, I think you want to use `forUnmatchedRequest()` (not `forAnyRequest()`). This defines a rule that only runs when no other rules match at all. That way your `forPost` rule will always run for those requests, but everything else will be proxied correctly.

Alternatively, you can use `forPost(...).always().` to define a rule that _always_ runs when it matches.

For more info, see the matching methods documentation [here](https://httptoolkit.github.io/mockttp/interfaces/Mockttp.html#forAnyRequest) and the rule completion methods (always, once, etc) [here](https://httptoolkit.github.io/mockttp/classes/RequestRuleBuilder.html#always).

I'm going to close this now, since I think that should cover this case. That is just my best guess at what's going on here, but it's hard to know more without a full example. If that doesn't work for you, please share a complete runnable example and a list of the requests you're making here, so I can reproduce what you're seeing and investigate further.

**Closed by pimterry** 2024-04-12 06:26 UTC
